"""
Daily Report Saver Hook Handler

Saves daily report content to markdown file when message is sent.
"""

import os
from datetime import datetime

from hook.hook_types import HookEvent, get_default_workspace_dir


def handler(event: HookEvent) -> None:
    """
    Handle message:sent events to save daily report.
    
    Args:
        event: The hook event
    """
    if event.type != "message" or event.action != "sent":
        return

    context = event.context
    if not isinstance(context, dict):
        return

    content = context.get("content", "")
    if not content:
        return

    workspace_dir = event.context.get("workspace_dir") or get_default_workspace_dir()

    reports_dir = os.path.join(workspace_dir, "reports")
    os.makedirs(reports_dir, exist_ok=True)

    today = datetime.now().strftime("%Y-%m-%d")
    filename = f"{today}.md"
    filepath = os.path.join(reports_dir, filename)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report_content = f"""# Daily Report - {today}

**Generated at**: {timestamp}

## Content

{content}

---
*This report was automatically generated by daily-report-saver hook.*
"""

    try:
        if os.path.exists(filepath):
            with open(filepath, "a", encoding="utf-8") as f:
                f.write(f"\n\n---\n\n## Update at {timestamp}\n\n{content}\n")
            print(f"[daily-report-saver] Appended to {filepath}")
        else:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(report_content)
            print(f"[daily-report-saver] Saved report to {filepath}")
        event.messages.append(f"📝 Daily report saved to {filename}")
    except Exception as e:
        print(f"[daily-report-saver] Error saving report: {e}")


export = handler
